# Generated by Django 5.0.7 on 2024-08-12 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicatorNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireCrimperNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireCrimperLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedInsulationCrimperNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedInsulationCrimperLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedAnvilNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedAnvilLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedStabilizerCrimperNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedStabilizerCrimperLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedAnvilHolderNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedAnvilHolderLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedSupportingStopperNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedSupportingStopperLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedBaseNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedBaseLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalGuidePlateBNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalGuidePlateBLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireHolderNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireHolderLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedCuttingPunchWireHolderNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedCuttingPunchWireHolderLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalGuidePlateANumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalGuidePlateALevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedShearbladeNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedShearbladeLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedOuterShearbladeNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedOuterShearbladeLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedFeedingClawNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedFeedingClawLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedInsulationAdjustingPieceNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedInsulationAdjustingPieceLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedBushNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedBushLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedFeedingCamNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedFeedingCamLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireStopperAssyNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireStopperAssyLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalScrapperNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalScrapperLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedSupportingStopperSpringNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedSupportingStopperSpringLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireHolderSpringNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireHolderSpringLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderSpringNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderSpringLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedBracketNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedBracketLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedRamNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedRamLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedInstallationPlateNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedInstallationPlateLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedSubAssyNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedSubAssyLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalOilPodUnitNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalOilPodUnitLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderSetToolNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderSetToolLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireStrandCompressorNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedWireStrandCompressorLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedConductorHolderNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedConductorHolderLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedConductorHolderSpringNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedConductorHolderSpringLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedCuttingPunchHolderNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedCuttingPunchHolderLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedInsulationAdjustingPeaceNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedInsulationAdjustingPeaceLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedOuterShareBladeNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedOuterShareBladeLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderAssyNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderAssyLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderaNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderaLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderbNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedTerminalHolderbLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedBaseTipNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedBaseTipLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedHexSocketboltNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('combinedHexSocketboltLevel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'applicatorData',
            },
        ),
        migrations.CreateModel(
            name='ApplicatorPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicatorNumber', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'aplicatorPart',
            },
        ),
        migrations.CreateModel(
            name='Carline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'carline',
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'excelTable',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDash', models.CharField(max_length=100)),
                ('numberDash', models.IntegerField()),
                ('levelDash', models.CharField(max_length=100)),
                ('categoryDash', models.CharField(max_length=100)),
                ('januaryDash', models.IntegerField(default=0)),
                ('februaryDash', models.IntegerField(default=0)),
                ('marchDash', models.IntegerField(default=0)),
                ('aprilDash', models.IntegerField(default=0)),
                ('mayDash', models.IntegerField(default=0)),
                ('juneDash', models.IntegerField(default=0)),
                ('averageDash', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNameMachine', models.CharField(blank=True, max_length=255, null=True)),
                ('partNumberMachine', models.CharField(blank=True, max_length=255, null=True)),
                ('levelMarkingMachine', models.CharField(blank=True, max_length=255, null=True)),
                ('machineNumberMachine', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'machine',
            },
        ),
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan1', models.CharField(blank=True, max_length=255, null=True)),
                ('bulan2', models.CharField(blank=True, max_length=255, null=True)),
                ('bulan3', models.CharField(blank=True, max_length=255, null=True)),
                ('bulan4', models.CharField(blank=True, max_length=255, null=True)),
                ('bulan5', models.CharField(blank=True, max_length=255, null=True)),
                ('bulan6', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'monthly',
            },
        ),
        migrations.CreateModel(
            name='PartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'partName',
            },
        ),
        migrations.CreateModel(
            name='SealUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNameSealUnit', models.CharField(blank=True, max_length=255, null=True)),
                ('partNumberSealUnit', models.CharField(blank=True, max_length=255, null=True)),
                ('levelMarkingSealUnit', models.CharField(blank=True, max_length=255, null=True)),
                ('machineNumberSealUnit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sealUnit',
            },
        ),
        migrations.CreateModel(
            name='PartDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('partCode', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('marking', models.CharField(blank=True, max_length=255, null=True)),
                ('applicatorNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.applicatorpart')),
                ('partName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.partname')),
            ],
            options={
                'db_table': 'partDesk',
            },
        ),
        migrations.CreateModel(
            name='ProducPlanQTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assyNo', models.CharField(blank=True, max_length=255, null=True)),
                ('loadJan', models.IntegerField(default=0)),
                ('loadFeb', models.IntegerField(default=0)),
                ('loadMarch', models.IntegerField(default=0)),
                ('loadApr', models.IntegerField(default=0)),
                ('loadMay', models.IntegerField(default=0)),
                ('loadJun', models.IntegerField(default=0)),
                ('carline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produc_plans', to='myapp.carline')),
                ('monthly_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.monthlydata')),
            ],
            options={
                'db_table': 'qty',
            },
        ),
    ]
