# Generated by Django 5.0.7 on 2025-05-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicatorPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicatorNumber', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'aplicatorPart',
            },
        ),
        migrations.CreateModel(
            name='CalculationResultLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField(default=2025)),
                ('result', models.FloatField()),
            ],
            options={
                'db_table': 'calculation_result_loading',
            },
        ),
        migrations.CreateModel(
            name='Carline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'carline',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'departement',
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'excelTable',
            },
        ),
        migrations.CreateModel(
            name='Load_applicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loading', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='applicator_images/')),
            ],
            options={
                'db_table': 'stroke',
            },
        ),
        migrations.CreateModel(
            name='NoAssy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noAssy', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'noAssy',
            },
        ),
        migrations.CreateModel(
            name='PartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'partName',
            },
        ),
        migrations.CreateModel(
            name='AggregatedResultByTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=10)),
                ('total_result', models.FloatField()),
                ('calculation_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.calculationresultloading')),
            ],
            options={
                'db_table': 'aggregated_result_terminal',
                'ordering': ['terminal', 'month'],
            },
        ),
        migrations.AddField(
            model_name='calculationresultloading',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results_loading', to='myapp.carline'),
        ),
        migrations.CreateModel(
            name='Bulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JAN', models.IntegerField(blank=True, null=True)),
                ('FEB', models.IntegerField(blank=True, null=True)),
                ('MAR', models.IntegerField(blank=True, null=True)),
                ('APR', models.IntegerField(blank=True, null=True)),
                ('MAY', models.IntegerField(blank=True, null=True)),
                ('JUN', models.IntegerField(blank=True, null=True)),
                ('JUL', models.IntegerField(blank=True, null=True)),
                ('AUG', models.IntegerField(blank=True, null=True)),
                ('SEP', models.IntegerField(blank=True, null=True)),
                ('OCT', models.IntegerField(blank=True, null=True)),
                ('NOV', models.IntegerField(blank=True, null=True)),
                ('DEC', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('carline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulans', to='myapp.carline')),
            ],
            options={
                'db_table': 'bulan',
            },
        ),
        migrations.CreateModel(
            name='LastRoundup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounded_loading', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(default=2025)),
                ('calculation_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.calculationresultloading')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_roundup', to='myapp.aggregatedresultbyterminal')),
                ('terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_roundup', to='myapp.aggregatedresultbyterminal')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicator_roundup', to='myapp.load_applicator')),
            ],
            options={
                'db_table': 'last_roundup',
            },
        ),
        migrations.CreateModel(
            name='MachineLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(blank=True, max_length=255, null=True)),
                ('noControl', models.CharField(blank=True, max_length=255, null=True)),
                ('kind', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('twist', models.CharField(blank=True, max_length=255, null=True)),
                ('termB', models.CharField(blank=True, max_length=255, null=True)),
                ('manB', models.CharField(blank=True, max_length=255, null=True)),
                ('accB1', models.CharField(blank=True, max_length=255, null=True)),
                ('termA', models.CharField(blank=True, max_length=255, null=True)),
                ('manA', models.CharField(blank=True, max_length=255, null=True)),
                ('accA1', models.CharField(blank=True, max_length=255, null=True)),
                ('carline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineLoading', to='myapp.carline')),
            ],
            options={
                'db_table': 'machine_loading',
            },
        ),
        migrations.CreateModel(
            name='AssyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noAssy', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('noControl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assy_values', to='myapp.machineloading')),
                ('termA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assy_value_termA_results', to='myapp.machineloading')),
                ('termB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assy_value_termB_results', to='myapp.machineloading')),
            ],
            options={
                'db_table': 'assy_value',
            },
        ),
        migrations.CreateModel(
            name='PartDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('partCode', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('marking', models.CharField(blank=True, max_length=255, null=True)),
                ('applicatorNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.applicatorpart')),
                ('partName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.partname')),
            ],
            options={
                'db_table': 'partDesk',
            },
        ),
        migrations.CreateModel(
            name='LoadingPartResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('terminal', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=10)),
                ('last_loading', models.FloatField(blank=True, null=True)),
                ('rounded_loading', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('average_round', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(default=2025)),
                ('carline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.carline')),
                ('partdesk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.partdesk')),
            ],
            options={
                'db_table': 'loading_part_result',
                'unique_together': {('carline', 'part_name', 'terminal', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('bulan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.bulan')),
                ('carline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.carline')),
                ('noAssy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.noassy')),
            ],
            options={
                'db_table': 'isiBulan',
            },
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('registered_no', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('purchase_by', models.CharField(max_length=100)),
                ('requested', models.BooleanField(default=False)),
                ('spv_approved', models.CharField(blank=True, max_length=100, null=True)),
                ('sspv_approved', models.CharField(blank=True, max_length=100, null=True)),
                ('carlines', models.ManyToManyField(to='myapp.carline')),
            ],
            options={
                'db_table': 'request_form',
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_ref_no', models.CharField(max_length=100)),
                ('result_average_round', models.IntegerField()),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deadline', models.CharField(max_length=100)),
                ('loading_part_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loadingpartresult')),
                ('request_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.requestform')),
            ],
            options={
                'db_table': 'request_item',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departement')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('registered_no', models.CharField(max_length=100, unique=True)),
                ('purchase_by', models.CharField(max_length=255)),
                ('budget_ref_no', models.CharField(max_length=100)),
                ('estimated_price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('requested', models.BooleanField(default=False)),
                ('spv_approved', models.BooleanField(default=False)),
                ('sspv_approved', models.BooleanField(default=False)),
                ('part_order', models.ManyToManyField(to='myapp.carline')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.section')),
            ],
            options={
                'db_table': 'purchase_request',
            },
        ),
        migrations.CreateModel(
            name='TerminalNameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_loading', models.FloatField(blank=True, null=True)),
                ('calculation_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.calculationresultloading')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_mapping', to='myapp.aggregatedresultbyterminal')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicator_mapping', to='myapp.load_applicator')),
                ('terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mapping', to='myapp.aggregatedresultbyterminal')),
                ('total_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='myapp.aggregatedresultbyterminal')),
            ],
            options={
                'db_table': 'terminal_name_mapping',
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('year', models.IntegerField(default=2025)),
                ('result', models.IntegerField()),
                ('carline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='myapp.carline')),
                ('noControl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_no_control_results', to='myapp.machineloading')),
                ('termA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_termA_results', to='myapp.machineloading')),
                ('termB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_termB_results', to='myapp.machineloading')),
            ],
            options={
                'db_table': 'calculation_result',
                'unique_together': {('carline', 'noControl', 'month', 'year')},
            },
        ),
    ]
