# Generated by Django 5.0.7 on 2025-06-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approve_factory_manager',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approve_manager',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='reason_factory_manager',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='reason_manager',
            field=models.TextField(blank=True, null=True),
        ),
    ]
