# Generated by Django 5.0.7 on 2024-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydata',
            name='tahun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
