# Generated by Django 5.0.7 on 2025-05-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
