# Generated by Django 5.0.7 on 2025-05-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
