# Generated by Django 5.0.7 on 2025-05-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_requestform_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
