# Generated by Django 5.0.7 on 2025-06-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_purchaseorder_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='cc',
        ),
        migrations.AddField(
            model_name='supplier',
            name='cc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
