# Generated by Django 5.2.4 on 2025-07-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stock_source_request_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='sc_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sc_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
