# Generated by Django 5.0.7 on 2025-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_purchaserequest_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approve_spv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approve_sspv',
            field=models.BooleanField(default=False),
        ),
    ]
