# Generated by Django 5.0.7 on 2024-08-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_monthlydata_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdesk',
            name='marking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
