# Generated by Django 5.0.7 on 2025-05-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_purchaserequest_approve_spv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.departement'),
        ),
    ]
