# Generated by Django 5.0.7 on 2024-08-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_partdesk_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdesk',
            name='marking',
            field=models.CharField(blank=True, null=True),
        ),
    ]
