# Generated by Django 5.0.7 on 2025-06-15 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_purchaseorder_cc_supplier_cc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('PartName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.partname')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
