# Generated by Django 5.2.4 on 2025-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_aggregatedresultbyterminal_calculation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('partial', 'Partial'), ('done', 'Done')], default='pending', max_length=10, null=True),
        ),
    ]
