# Generated by Django 5.0.7 on 2025-05-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_purchaserequest_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='approve_spv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='approve_sspv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='registered_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
