# Generated by Django 5.0.7 on 2024-08-15 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_bulan_month_name_bulan_apr_bulan_aug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='bulan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.bulan'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3),
        ),
        migrations.AlterModelTable(
            name='bulan',
            table='bulan',
        ),
        migrations.AlterModelTable(
            name='quantity',
            table='isiBulan',
        ),
    ]
