# Generated by Django 5.0.7 on 2025-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='attn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
