# Generated by Django 5.0.7 on 2025-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_purchaserequest_approve_spv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='estimated_price',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
