# Generated by Django 5.0.7 on 2025-06-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_supplier_attn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
