# Generated by Django 5.0.7 on 2024-08-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_quantity_bulan_alter_quantity_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='bulan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.bulan'),
        ),
    ]
