# Generated by Django 5.2.4 on 2025-07-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_purchaserequest_stock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='stock_status',
        ),
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='calculation_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.calculationresultloading'),
        ),
    ]
