# Generated by Django 5.0.7 on 2024-08-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_quantity_bulan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bulan',
            table='janDec',
        ),
        migrations.AlterModelTable(
            name='quantity',
            table=None,
        ),
    ]
