# Generated by Django 5.0.7 on 2024-08-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_partdesk_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdesk',
            name='marking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
