# Generated by Django 5.0.7 on 2025-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_requestitem_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='estimated_price',
            field=models.FloatField(default=0),
        ),
    ]
