# Generated by Django 5.0.7 on 2025-05-23 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_requestitem_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='budget_ref_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
