# Generated by Django 5.0.7 on 2024-08-13 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_partdesk_marking'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydata',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data', to='myapp.carline'),
        ),
    ]
