# Generated by Django 5.0.7 on 2025-06-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
