# Generated by Django 5.0.7 on 2024-08-15 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_bulan_table_alter_quantity_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quantity',
            table='isiBulan',
        ),
    ]
