# Generated by Django 5.2.4 on 2025-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_aggregatedresultbyterminal_calculation_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='quantity_defect',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_missing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity_real',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
