# Generated by Django 5.0.7 on 2024-08-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_monthlydata_carline'),
    ]

    operations = [
        migrations.AddField(
            model_name='producplanqty',
            name='loadAug',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producplanqty',
            name='loadDec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producplanqty',
            name='loadJul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producplanqty',
            name='loadNov',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producplanqty',
            name='loadOct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producplanqty',
            name='loadSep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producplanqty',
            name='loadApr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producplanqty',
            name='loadFeb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producplanqty',
            name='loadJan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producplanqty',
            name='loadJun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producplanqty',
            name='loadMarch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producplanqty',
            name='loadMay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
