# Generated by Django 5.0.7 on 2024-08-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_quantity_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoAssy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noAssy', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'noAssy',
            },
        ),
        migrations.AddField(
            model_name='quantity',
            name='noAssy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.noassy'),
        ),
    ]
