# Generated by Django 5.0.7 on 2025-05-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_requestitem_budget_ref_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
