# Generated by Django 5.0.7 on 2025-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_purchaseorder_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
