# Generated by Django 5.0.7 on 2025-06-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_purchaseorder_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('acc_rej', models.BooleanField(blank=True, null=True)),
                ('registered_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest')),
            ],
            options={
                'db_table': 'schedule_conf',
            },
        ),
    ]
