# Generated by Django 5.0.7 on 2024-08-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_producplanqty_loadaug_producplanqty_loaddec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='augustDash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='decemberDash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='julyDash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='novemberDash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='octoberDash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='septemberDash',
            field=models.IntegerField(default=0),
        ),
    ]
