# Generated by Django 5.0.7 on 2025-06-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_requestitem_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('tel_no', models.CharField(max_length=100, unique=True)),
                ('fax_no', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
