# Generated by Django 5.0.7 on 2024-08-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_noassy_quantity_noassy'),
        ('myapp', '0010_item_augustdash_item_decemberdash_item_julydash_and_more'),
    ]

    operations = [
    ]
