# Generated by Django 5.0.7 on 2025-06-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_scheduleconf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconf',
            name='registered_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
