# Generated by Django 5.0.7 on 2025-06-01 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('term', models.CharField(max_length=100)),
                ('delivery', models.DateField(blank=True, null=True)),
                ('shipped_by', models.CharField(max_length=100)),
                ('registered_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
            options={
                'db_table': 'purchase_order',
            },
        ),
    ]
