# Generated by Django 5.0.7 on 2024-08-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_merge_20240815_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlydata',
            name='carline',
        ),
        migrations.AddField(
            model_name='quantity',
            name='carLine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.carline'),
        ),
    ]
