# Generated by Django 5.0.7 on 2025-06-01 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='registered_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest'),
        ),
    ]
