# Generated by Django 5.0.7 on 2025-06-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_scheduleconf_registered_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconf',
            name='registered_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest'),
        ),
    ]
