# Generated by Django 5.0.7 on 2025-06-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_purchaseorder_registered_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
