# Generated by Django 5.0.7 on 2025-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_scheduleconf_registered_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleconf',
            name='date',
        ),
        migrations.AddField(
            model_name='scheduleconf',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
