# Generated by Django 5.0.7 on 2024-08-16 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_monthlydata_carline_quantity_carline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulan',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulans', to='myapp.carline'),
        ),
    ]
