# Generated by Django 5.0.7 on 2024-08-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_bulan_carline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producplanqty',
            name='monthly_data',
        ),
        migrations.RemoveField(
            model_name='producplanqty',
            name='carline',
        ),
        migrations.DeleteModel(
            name='MonthlyData',
        ),
        migrations.DeleteModel(
            name='ProducPlanQTY',
        ),
    ]
