# Generated by Django 5.0.7 on 2025-06-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_purchaserequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='reason_spv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='reason_sspv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
