# Generated by Django 5.0.7 on 2025-06-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_scheduleconf_date_scheduleconf_send_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleconf',
            name='send_date',
        ),
        migrations.AddField(
            model_name='scheduleconf',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
