# Generated by Django 5.0.7 on 2024-08-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_producplanqty_monthly_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicator',
        ),
    ]
