# Generated by Django 5.0.7 on 2025-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_purchaserequest_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shipped',
            },
        ),
    ]
