# Generated by Django 5.0.7 on 2025-06-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_scheduleconf_send_date_scheduleconf_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airwaybill_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('weight', models.CharField(max_length=100)),
                ('shipping_cost', models.CharField(max_length=100)),
                ('registered_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest')),
            ],
            options={
                'db_table': 'air_way_bill',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('last_amount', models.FloatField(default=0)),
                ('registered_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaserequest')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
