# Generated by Django 5.0.7 on 2025-06-06 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.shipped'),
        ),
    ]
