# Generated by Django 5.0.7 on 2024-08-20 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_applicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('termB', models.CharField(blank=True, null=True)),
                ('manB', models.CharField(blank=True, null=True)),
                ('accB1', models.CharField(blank=True, null=True)),
                ('termA', models.CharField(blank=True, null=True)),
                ('manA', models.CharField(blank=True, null=True)),
                ('accA1', models.CharField(blank=True, null=True)),
                ('assy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcl', to='myapp.noassy')),
                ('carline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcl', to='myapp.carline')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcl', to='myapp.machine')),
            ],
            options={
                'db_table': 'mcl_table',
            },
        ),
    ]
