# Generated by Django 5.0.7 on 2024-08-21 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_mcl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcl',
            name='accA1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='accB1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='assy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcl_assy', to='myapp.noassy'),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcl_carline', to='myapp.carline'),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='kind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcl_machine', to='myapp.machine'),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='manA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='manB',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='termA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcl',
            name='termB',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
