# Generated by Django 5.0.7 on 2024-08-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_mcl_acca1_alter_mcl_accb1_alter_mcl_assy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='machineNumber',
            field=models.IntegerField(default=0),
        ),
    ]
