# Generated by Django 5.0.7 on 2024-08-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_item_machinenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='bulan',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='carLine',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='noAssy',
        ),
        migrations.AddField(
            model_name='noassy',
            name='bulan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.bulan'),
        ),
        migrations.AddField(
            model_name='noassy',
            name='carLine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='noassy',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.quantity'),
        ),
    ]
