# Generated by Django 5.0.7 on 2024-08-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_noassy_bulan_remove_noassy_carline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noassy',
            name='noAssy',
        ),
        migrations.CreateModel(
            name='SppAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sppall', to='myapp.bulan')),
                ('carLine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sppall', to='myapp.carline')),
                ('noAssy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sppall', to='myapp.noassy')),
                ('quantity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sppall', to='myapp.quantity')),
            ],
            options={
                'db_table': 'spp_all',
            },
        ),
    ]
