# Generated by Django 5.0.7 on 2024-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_noassy_noassy_sppall'),
    ]

    operations = [
        migrations.AddField(
            model_name='noassy',
            name='noAssy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
