# Generated by Django 5.0.7 on 2024-08-23 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_noassy_noassy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='bulan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.bulan'),
        ),
        migrations.DeleteModel(
            name='SppAll',
        ),
    ]
