# Generated by Django 5.0.7 on 2024-08-23 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_quantity_bulan_delete_sppall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='bulan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='myapp.bulan'),
        ),
    ]
