# Generated by Django 5.0.7 on 2024-08-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_quantity_bulan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='carLine',
            new_name='carline',
        ),
        migrations.RemoveField(
            model_name='bulan',
            name='carline',
        ),
    ]
