# Generated by Django 5.0.7 on 2024-08-23 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_carline_quantity_carline_remove_bulan_carline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='carline',
            new_name='carLine',
        ),
        migrations.AddField(
            model_name='bulan',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulans', to='myapp.carline'),
        ),
    ]
