# Generated by Django 5.0.7 on 2024-08-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_carline_quantity_carline_bulan_carline'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcl',
            name='twist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
