# Generated by Django 5.0.7 on 2024-08-26 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_mcl_twist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('twist', models.IntegerField()),
                ('termB', models.IntegerField()),
                ('manB', models.IntegerField()),
                ('accB1', models.IntegerField()),
                ('termA', models.IntegerField()),
                ('manA', models.IntegerField()),
                ('accA1', models.IntegerField()),
                ('carline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.carline')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
                ('no_assy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.noassy')),
            ],
            options={
                'db_table': 'machine_loading',
            },
        ),
        migrations.CreateModel(
            name='AssyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
                ('no_assy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.noassy')),
                ('machine_loading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machineloading')),
            ],
            options={
                'db_table': 'assy_value',
            },
        ),
        migrations.DeleteModel(
            name='MCL',
        ),
    ]
