# Generated by Django 5.0.7 on 2024-08-26 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_machineloading_assyvalue_delete_mcl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='noAssy',
            new_name='no_assy',
        ),
        migrations.RemoveField(
            model_name='assyvalue',
            name='key',
        ),
        migrations.AddField(
            model_name='assyvalue',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assyValue', to='myapp.machine'),
        ),
        migrations.AlterField(
            model_name='assyvalue',
            name='machine_loading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assyValue', to='myapp.machineloading'),
        ),
        migrations.AlterField(
            model_name='assyvalue',
            name='no_assy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assyValue', to='myapp.noassy'),
        ),
        migrations.AlterField(
            model_name='machineloading',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineLoading', to='myapp.carline'),
        ),
        migrations.AlterField(
            model_name='machineloading',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineLoading', to='myapp.machine'),
        ),
        migrations.AlterField(
            model_name='machineloading',
            name='no_assy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineLoading', to='myapp.noassy'),
        ),
    ]
