# Generated by Django 5.0.7 on 2024-08-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_rename_noassy_quantity_no_assy_remove_assyvalue_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='no_assy',
            new_name='noAssy',
        ),
    ]
