# Generated by Django 5.0.7 on 2024-08-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_rename_no_assy_quantity_noassy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assyvalue',
            name='machine_loading',
        ),
        migrations.RemoveField(
            model_name='machineloading',
            name='no_assy',
        ),
        migrations.AlterField(
            model_name='assyvalue',
            name='value',
            field=models.BooleanField(),
        ),
    ]
