# Generated by Django 5.0.7 on 2024-08-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_assyvalue_machine_loading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assyvalue',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='machineloading',
            name='machine',
        ),
    ]
