# Generated by Django 5.0.7 on 2024-08-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_assyvalue_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assyvalue',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assyValue', to='myapp.machine'),
        ),
        migrations.AddField(
            model_name='machineloading',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineLoading', to='myapp.machine'),
        ),
    ]
