# Generated by Django 5.0.7 on 2024-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_machineloading_machine_machineloading_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineloading',
            name='machine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
