# Generated by Django 5.0.7 on 2024-08-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_machineloading_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noAssy', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.BooleanField()),
            ],
            options={
                'db_table': 'assy_value',
            },
        ),
    ]
