# Generated by Django 5.0.7 on 2024-08-27 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_assyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='assyvalue',
            name='machineLoading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assyValue', to='myapp.machineloading'),
        ),
    ]
