# Generated by Django 5.0.7 on 2024-08-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_assyvalue_machineloading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assyvalue',
            old_name='machineLoading',
            new_name='noControl',
        ),
        migrations.AddField(
            model_name='machineloading',
            name='noControl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
