# Generated by Django 5.0.7 on 2024-08-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_machineloading_assyvalue_nocontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assyvalue',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
