# Generated by Django 5.0.7 on 2024-08-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_assyvalue_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noAssy', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=3)),
                ('result', models.IntegerField()),
            ],
            options={
                'db_table': 'calculation_result',
            },
        ),
    ]
