# Generated by Django 5.0.7 on 2024-08-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_calculationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='noControl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
