# Generated by Django 5.0.7 on 2024-08-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_calculationresult_nocontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='myapp.carline'),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='noAssy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
