# Generated by Django 5.0.7 on 2024-08-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_calculationresult_carline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='noControl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='myapp.machineloading'),
        ),
    ]
