# Generated by Django 5.0.7 on 2024-08-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_calculationresult_nocontrol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calculationresult',
            unique_together={('carline', 'noControl', 'month')},
        ),
    ]
