# Generated by Django 5.0.7 on 2024-08-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_calculationresult_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationresult',
            name='noAssy',
        ),
    ]
