# Generated by Django 5.0.7 on 2024-08-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_calculationresult_noassy'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='noAssy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
