# Generated by Django 5.0.7 on 2024-08-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_calculationresult_noassy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationresult',
            name='noAssy',
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='termA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_termA_results', to='myapp.machineloading'),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='termB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_termB_results', to='myapp.machineloading'),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='noControl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_no_control_results', to='myapp.machineloading'),
        ),
    ]
