# Generated by Django 5.0.7 on 2024-08-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_calculationresult_noassy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assyvalue',
            name='termA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assy_value_termA_results', to='myapp.machineloading'),
        ),
        migrations.AddField(
            model_name='assyvalue',
            name='termB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assy_value_termB_results', to='myapp.machineloading'),
        ),
        migrations.AlterField(
            model_name='assyvalue',
            name='noControl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assy_values', to='myapp.machineloading'),
        ),
    ]
