# Generated by Django 5.0.7 on 2024-08-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_assyvalue_terma_assyvalue_termb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assyvalue',
            name='termA',
        ),
        migrations.RemoveField(
            model_name='assyvalue',
            name='termB',
        ),
    ]
