# Generated by Django 5.0.7 on 2024-08-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_remove_assyvalue_terma_remove_assyvalue_termb'),
    ]

    operations = [
        migrations.AddField(
            model_name='assyvalue',
            name='termA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assy_value_termA_results', to='myapp.machineloading'),
        ),
        migrations.AddField(
            model_name='assyvalue',
            name='termB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assy_value_termB_results', to='myapp.machineloading'),
        ),
    ]
