# Generated by Django 5.0.7 on 2024-08-30 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_assyvalue_terma_assyvalue_termb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResultLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=10)),
                ('result', models.FloatField()),
                ('result_divided', models.FloatField()),
                ('carline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results_loading', to='myapp.carline')),
            ],
            options={
                'db_table': 'calculation_result_loading',
            },
        ),
    ]
