# Generated by Django 5.0.7 on 2024-08-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_calculationresultloading'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedResultByTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=3)),
                ('total_result', models.FloatField()),
            ],
        ),
    ]
