# Generated by Django 5.0.7 on 2024-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_aggregatedresultbyterminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundedResultByTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=3)),
                ('rounded_result', models.IntegerField()),
            ],
        ),
    ]
