# Generated by Django 5.0.7 on 2024-08-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_roundedresultbyterminal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aggregatedresultbyterminal',
            table='aggregated_result_Terminal',
        ),
        migrations.AlterModelTable(
            name='roundedresultbyterminal',
            table='round_up',
        ),
    ]
