# Generated by Django 5.0.7 on 2024-08-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_aggregatedresultbyterminal_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundedresultbyterminal',
            old_name='terminal',
            new_name='term_round',
        ),
    ]
