# Generated by Django 5.0.7 on 2024-09-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_rename_terminal_roundedresultbyterminal_term_round'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calculationresult',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='noControl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='termA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='termB',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='calculationresult',
            unique_together={('carline', 'noControl', 'termB', 'termA', 'month')},
        ),
    ]
