# Generated by Django 5.0.7 on 2024-09-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_alter_calculationresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calculationresult',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='noControl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_no_control_results', to='myapp.machineloading'),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='termA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_termA_results', to='myapp.machineloading'),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='termB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_termB_results', to='myapp.machineloading'),
        ),
        migrations.AlterUniqueTogether(
            name='calculationresult',
            unique_together={('carline', 'noControl', 'month')},
        ),
    ]
