# Generated by Django 5.0.7 on 2024-09-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_alter_calculationresult_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsCalculateLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=100)),
                ('name_dash', models.CharField(blank=True, max_length=255, null=True)),
                ('number_dash', models.CharField(blank=True, max_length=255, null=True)),
                ('level_dash', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(max_length=50)),
                ('january_dash', models.IntegerField(blank=True, null=True)),
                ('february_dash', models.IntegerField(blank=True, null=True)),
                ('march_dash', models.IntegerField(blank=True, null=True)),
                ('april_dash', models.IntegerField(blank=True, null=True)),
                ('may_dash', models.IntegerField(blank=True, null=True)),
                ('june_dash', models.IntegerField(blank=True, null=True)),
                ('july_dash', models.IntegerField(blank=True, null=True)),
                ('august_dash', models.IntegerField(blank=True, null=True)),
                ('september_dash', models.IntegerField(blank=True, null=True)),
                ('oktober_dash', models.IntegerField(blank=True, null=True)),
                ('november_dash', models.IntegerField(blank=True, null=True)),
                ('december_dash', models.IntegerField(blank=True, null=True)),
                ('average_dash', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'views_calculate_load',
            },
        ),
    ]
