# Generated by Django 5.0.7 on 2024-09-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_viewscalculateload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='carLine',
            new_name='carline',
        ),
    ]
