# Generated by Django 5.0.7 on 2024-09-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_rename_carline_quantity_carline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load_applicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loading', models.IntegerField()),
            ],
        ),
    ]
