# Generated by Django 5.0.7 on 2024-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_load_applicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_applicator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applicator_images/'),
        ),
    ]
