# Generated by Django 5.0.7 on 2024-09-05 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_aggregatedresultbyterminal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedresultbyterminal',
            name='loading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregatedResultByTerminalLoading', to='myapp.load_applicator'),
        ),
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregatedResultByTerminalName', to='myapp.load_applicator'),
        ),
    ]
