# Generated by Django 5.0.7 on 2024-09-06 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_aggregatedresultbyterminal_loading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatedresultbyterminal',
            name='loading',
        ),
        migrations.RemoveField(
            model_name='aggregatedresultbyterminal',
            name='name',
        ),
        migrations.CreateModel(
            name='TerminalNameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicator_mapping', to='myapp.load_applicator')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mapping', to='myapp.calculationresultloading')),
            ],
            options={
                'db_table': 'terminal_name_mapping',
            },
        ),
    ]
