# Generated by Django 5.0.7 on 2024-09-06 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_remove_aggregatedresultbyterminal_loading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalnamemapping',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_mapping', to='myapp.aggregatedresultbyterminal'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='total_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='terminalnamemapping',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicator_mapping', to='myapp.load_applicator'),
        ),
        migrations.AlterField(
            model_name='terminalnamemapping',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mapping', to='myapp.calculationresultloading'),
        ),
    ]
