# Generated by Django 5.0.7 on 2024-09-06 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_alter_terminalnamemapping_total_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalnamemapping',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mapping', to='myapp.aggregatedresultbyterminal'),
        ),
    ]
