# Generated by Django 5.0.7 on 2024-09-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_alter_terminalnamemapping_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalnamemapping',
            name='last_loading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
