# Generated by Django 5.0.7 on 2024-09-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_terminalnamemapping_last_loading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3),
        ),
    ]
