# Generated by Django 5.0.7 on 2024-09-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_alter_aggregatedresultbyterminal_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='month',
            field=models.CharField(max_length=3),
        ),
    ]
