# Generated by Django 5.0.7 on 2024-09-09 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_alter_terminalnamemapping_total_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRoundup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounded_loading', models.FloatField(blank=True, null=True)),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_roundup', to='myapp.aggregatedresultbyterminal')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicator_roundup', to='myapp.load_applicator')),
                ('terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_roundup', to='myapp.aggregatedresultbyterminal')),
            ],
            options={
                'db_table': 'last_roundup',
            },
        ),
    ]
