# Generated by Django 5.0.7 on 2024-09-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_lastroundup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('part_code', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('marking', models.CharField(blank=True, max_length=255, null=True)),
                ('rounded_loading', models.FloatField(blank=True, null=True)),
                ('applicator_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combined_applicator', to='myapp.applicatorpart')),
                ('last_roundup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_roundup', to='myapp.lastroundup')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combined_month', to='myapp.aggregatedresultbyterminal')),
                ('part_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_partdesk', to='myapp.partdesk')),
                ('part_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.partname')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combined_terminal', to='myapp.aggregatedresultbyterminal')),
            ],
            options={
                'db_table': 'combined_App_MCL',
            },
        ),
    ]
