# Generated by Django 5.0.7 on 2024-09-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_combinedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombinedModel',
        ),
    ]
