# Generated by Django 5.0.7 on 2024-09-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_delete_combinedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_roundup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_last_roundup', to='myapp.lastroundup')),
                ('part_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_part_desk', to='myapp.partdesk')),
            ],
            options={
                'db_table': 'combined_model',
            },
        ),
    ]
