# Generated by Django 5.0.7 on 2024-09-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_delete_roundedresultbyterminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicatorPartAvarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('part_code', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('marking', models.CharField(blank=True, max_length=100, null=True)),
                ('jan', models.FloatField(blank=True, null=True)),
                ('feb', models.FloatField(blank=True, null=True)),
                ('mar', models.FloatField(blank=True, null=True)),
                ('apr', models.FloatField(blank=True, null=True)),
                ('may', models.FloatField(blank=True, null=True)),
                ('jun', models.FloatField(blank=True, null=True)),
                ('jul', models.FloatField(blank=True, null=True)),
                ('aug', models.FloatField(blank=True, null=True)),
                ('sep', models.FloatField(blank=True, null=True)),
                ('oct', models.FloatField(blank=True, null=True)),
                ('nov', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applicator_part_average',
            },
        ),
    ]
