# Generated by Django 5.0.7 on 2024-09-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_remove_calculationresultloading_result_divided'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarlineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
