# Generated by Django 5.0.7 on 2024-09-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_carlinemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarlineModel',
        ),
        migrations.AlterModelTable(
            name='load_applicator',
            table='stroke',
        ),
    ]
