# Generated by Django 5.0.7 on 2024-09-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_delete_carlinemodel_alter_load_applicator_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregatedresultbyterminal',
            options={'ordering': ['terminal', 'month']},
        ),
    ]
