# Generated by Django 5.0.7 on 2025-04-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_alter_applicatorpartavarage_apr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='SealUnit',
        ),
    ]
