# Generated by Django 5.0.7 on 2025-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0084_delete_machine_delete_sealunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredNo', models.CharField(max_length=100)),
                ('deptartemen', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('purchaseReqBy', models.CharField(max_length=100)),
                ('budgetReqNo', models.IntegerField(default=0)),
                ('estimatedPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('machineNumber', models.IntegerField(default=0)),
                ('nameDash', models.CharField(max_length=100)),
                ('averageDash', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'purchaseReq',
            },
        ),
    ]
