# Generated by Django 5.0.7 on 2025-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0085_purchasereq'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereq',
            name='carlines',
            field=models.ManyToManyField(blank=True, to='myapp.carline'),
        ),
    ]
