# Generated by Django 5.0.7 on 2025-04-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0086_purchasereq_carlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedresultbyterminal',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_result_by_terminal', to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_name_mapping', to='myapp.carline'),
        ),
    ]
