# Generated by Django 5.0.7 on 2025-04-30 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0087_aggregatedresultbyterminal_carline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregatedresultbyterminal',
            options={},
        ),
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_results', to='myapp.carline'),
        ),
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='terminal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='aggregatedresultbyterminal',
            table='aggregated_result_by_terminal',
        ),
    ]
