# Generated by Django 5.0.7 on 2025-04-30 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0088_alter_aggregatedresultbyterminal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastroundup',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carline_roundup', to='myapp.carline'),
        ),
        migrations.AlterField(
            model_name='terminalnamemapping',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mappings', to='myapp.carline'),
        ),
    ]
