# Generated by Django 5.0.7 on 2025-05-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0090_calculationresultloading_result_divided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_applicator',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
    ]
