# Generated by Django 5.0.7 on 2025-05-05 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0091_load_applicator_carline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicator_part_avarage', to='myapp.carline'),
        ),
    ]
