# Generated by Django 5.0.7 on 2025-05-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0092_alter_aggregatedresultbyterminal_carline'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicatorpartavarage',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
    ]
