# Generated by Django 5.0.7 on 2025-05-05 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0093_applicatorpartavarage_carline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='month',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='name',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='total_result',
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='aggregated_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.aggregatedresultbyterminal'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='applicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.load_applicator'),
        ),
        migrations.AlterField(
            model_name='terminalnamemapping',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
        migrations.AlterUniqueTogether(
            name='lastroundup',
            unique_together={('terminal', 'name')},
        ),
    ]
