# Generated by Django 5.0.7 on 2025-05-05 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0094_remove_terminalnamemapping_month_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lastroundup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='applicatorpartavarage',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='calculationresultloading',
            name='result_divided',
        ),
        migrations.RemoveField(
            model_name='load_applicator',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='aggregated_result',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='applicator',
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_mapping', to='myapp.aggregatedresultbyterminal'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicator_mapping', to='myapp.load_applicator'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mapping', to='myapp.aggregatedresultbyterminal'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='total_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='myapp.aggregatedresultbyterminal'),
        ),
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_results', to='myapp.carline'),
        ),
        migrations.AlterField(
            model_name='calculationresultloading',
            name='result',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calculationresultloading',
            name='terminal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='terminalnamemapping',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mappings', to='myapp.carline'),
        ),
    ]
