# Generated by Django 5.0.7 on 2025-05-05 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0095_alter_lastroundup_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='month',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='name',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='total_result',
        ),
        migrations.AddField(
            model_name='applicatorpartavarage',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='calculationresultloading',
            name='result_divided',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='load_applicator',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='aggregated_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.aggregatedresultbyterminal'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='applicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.load_applicator'),
        ),
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicator_part_avarage', to='myapp.carline'),
        ),
        migrations.AlterField(
            model_name='calculationresultloading',
            name='result',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculationresultloading',
            name='terminal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='terminalnamemapping',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
    ]
