# Generated by Django 5.0.7 on 2025-05-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0100_remove_calculationresultloading_result_divided'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregatedresultbyterminal',
            options={'ordering': ['terminal', 'month']},
        ),
        migrations.RemoveField(
            model_name='aggregatedresultbyterminal',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='lastroundup',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='carline',
        ),
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='terminal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='aggregatedresultbyterminal',
            table='aggregated_result_Terminal',
        ),
    ]
