# Generated by Django 5.0.7 on 2025-05-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0101_alter_aggregatedresultbyterminal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedresultbyterminal',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='applicatorpartavarage',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='lastroundup',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='load_applicator',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='partdesk',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='carline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.carline'),
        ),
    ]
