# Generated by Django 5.0.7 on 2025-05-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0102_aggregatedresultbyterminal_carline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatedresultbyterminal',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='applicatorpartavarage',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='lastroundup',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='load_applicator',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='partdesk',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='carline',
        ),
    ]
