# Generated by Django 5.0.7 on 2025-05-06 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0103_remove_aggregatedresultbyterminal_carline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedresultbyterminal',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_result', to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='applicatorpartavarage',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carline_avarage', to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='lastroundup',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carline_roundup', to='myapp.carline'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carline_mapping', to='myapp.carline'),
        ),
    ]
