# Generated by Django 5.0.7 on 2025-05-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0104_aggregatedresultbyterminal_carline_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aggregatedresultbyterminal',
            table='aggregated_result_terminal',
        ),
    ]
