# Generated by Django 5.0.7 on 2025-05-07 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0105_alter_aggregatedresultbyterminal_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedresultbyterminal',
            name='carline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.carline'),
        ),
    ]
