# Generated by Django 5.0.7 on 2025-05-07 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0106_alter_aggregatedresultbyterminal_carline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='month',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='total_result',
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_mapping', to='myapp.aggregatedresultbyterminal'),
        ),
    ]
