# Generated by Django 5.0.7 on 2025-05-07 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0108_remove_terminalnamemapping_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatedresultbyterminal',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='lastroundup',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='terminalnamemapping',
            name='carline',
        ),
        migrations.AddField(
            model_name='aggregatedresultbyterminal',
            name='calculation_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.calculationresultloading'),
        ),
        migrations.AddField(
            model_name='lastroundup',
            name='calculation_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.calculationresultloading'),
        ),
        migrations.AddField(
            model_name='terminalnamemapping',
            name='calculation_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.calculationresultloading'),
        ),
    ]
