# Generated by Django 5.0.7 on 2025-05-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0109_remove_aggregatedresultbyterminal_carline_and_more'),
    ]

    operations = [
    ]
