# Generated by Django 5.0.7 on 2025-05-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0114_alter_aggregatedresultbyterminal_calculation_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingPartResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('terminal', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=10)),
                ('last_loading', models.FloatField(blank=True, null=True)),
                ('rounded_loading', models.FloatField(blank=True, null=True)),
                ('carline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.carline')),
            ],
            options={
                'db_table': 'loading_part_result',
                'unique_together': {('carline', 'part_name', 'terminal', 'month')},
            },
        ),
    ]
