# Generated by Django 5.0.7 on 2025-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0115_loadingpartresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingpartresult',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
