# Generated by Django 5.0.7 on 2025-05-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0116_loadingpartresult_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadingpartresult',
            name='average',
        ),
    ]
