# Generated by Django 5.0.7 on 2025-05-14 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0118_loadingpartresult_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingpartresult',
            name='partdesk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.partdesk'),
        ),
    ]
