# Generated by Django 5.0.7 on 2025-05-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0119_loadingpartresult_partdesk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='purchaseReq',
        ),
    ]
