# Generated by Django 5.0.7 on 2025-05-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0120_delete_purchasereq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicatorpartavarage',
            name='carline',
        ),
        migrations.RemoveField(
            model_name='combinedmodel',
            name='last_roundup',
        ),
        migrations.RemoveField(
            model_name='combinedmodel',
            name='part_desk',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ViewsCalculateLoad',
        ),
        migrations.DeleteModel(
            name='ApplicatorPartAvarage',
        ),
        migrations.DeleteModel(
            name='CombinedModel',
        ),
    ]
