# Generated by Django 5.0.7 on 2025-05-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0121_remove_applicatorpartavarage_carline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingpartresult',
            name='average_round',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
