# Generated by Django 5.0.7 on 2025-05-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0122_loadingpartresult_average_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
