# Generated by Django 5.0.7 on 2025-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0123_quantity_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulan',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='bulan',
            table='bulan',
        ),
    ]
