# Generated by Django 5.0.7 on 2025-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0124_bulan_year_alter_bulan_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calculationresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='calculationresultloading',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterUniqueTogether(
            name='calculationresult',
            unique_together={('carline', 'noControl', 'month', 'year')},
        ),
    ]
