# Generated by Django 5.0.7 on 2025-05-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0125_alter_calculationresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingpartresult',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
