# Generated by Django 5.0.7 on 2025-05-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0126_loadingpartresult_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastroundup',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
