# Generated by Django 5.0.7 on 2025-05-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0127_lastroundup_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedresultbyterminal',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
