# Generated by Django 5.0.7 on 2025-05-14 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0128_aggregatedresultbyterminal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatedresultbyterminal',
            name='year',
        ),
    ]
