# Generated by Django 5.0.7 on 2025-05-15 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0129_remove_aggregatedresultbyterminal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departement')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('registered_no', models.CharField(max_length=100, unique=True)),
                ('purchase_by', models.CharField(max_length=255)),
                ('budget_ref_no', models.CharField(max_length=100)),
                ('estimated_price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('requested', models.BooleanField(default=False)),
                ('spv_approved', models.BooleanField(default=False)),
                ('sspv_approved', models.BooleanField(default=False)),
                ('part_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loadingpartresult')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.section')),
            ],
            options={
                'db_table': 'purchase_request',
            },
        ),
    ]
